"""Gera a estrutura de pastas definida em ARQUITETURA.md."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

DIRS = [
    # data
    "data/raw/programming/github/README files",
    "data/raw/programming/github/issues_discussions",
    "data/raw/programming/github/commits_history",
    "data/raw/programming/stackoverflow",
    "data/raw/programming/documentation/python_docs",
    "data/raw/programming/documentation/js_mdn",
    "data/raw/programming/documentation/rust_book",
    "data/raw/programming/documentation/golang_docs",
    "data/raw/programming/tutorials/course_materials",
    "data/raw/programming/tutorials/lecture_notes",
    "data/raw/programming/tutorials/code_examples",
    "data/raw/security/cve_nvd",
    "data/raw/security/cwe_data",
    "data/raw/security/owasp/cheat_sheets",
    "data/raw/security/owasp/security_guides",
    "data/raw/security/exploits",
    "data/raw/security/research_papers/ieee_abstracts",
    "data/raw/security/research_papers/cryptography_papers",
    "data/raw/security/threat_intelligence",
    "data/raw/security/compliance",
    "data/raw/metadata",
    "data/processed/programming/train",
    "data/processed/programming/validation",
    "data/processed/programming/test",
    "data/processed/security/train",
    "data/processed/security/validation",
    "data/processed/security/test",
    "data/processed/merged",
    "data/processed/augmented",
    "data/validation",
    "data/cache/tokenizer_cache",
    "data/cache/embedding_cache",
    "data/cache/processed_chunks",
    "data/statistics",
    "data/config",
    # models
    "models/pretrained/syon-7b",
    "models/pretrained/syon-13b",
    "models/pretrained/syon-70b",
    "models/quantized/syon-7b-gguf/q4_0",
    "models/quantized/syon-7b-gguf/q5_0",
    "models/quantized/syon-7b-gguf/q8_0",
    "models/quantized/syon-13b-gguf",
    "models/quantized/syon-70b-gguf",
    "models/quantized/gptq/syon-7b-gptq",
    "models/quantized/gptq/syon-13b-gptq",
    "models/quantized/awq/syon-7b-awq",
    "models/quantized/awq/syon-13b-awq",
    "models/finetuned/syon-7b-code-instruct/adapters",
    "models/finetuned/syon-13b-security-expert/adapters",
    "models/finetuned/syon-7b-multilingual",
    "models/adapters/code_completion_lora",
    "models/adapters/security_analysis_lora",
    "models/adapters/prompt_following_lora",
    "models/embeddings",
    "models/tokenizers",
    "models/onnx/syon-7b-onnx",
    "models/onnx/syon-13b-onnx",
    "models/tflite",
    "models/metadata",
    "models/vocabulary",
    "models/logs",
    # training
    "training/core",
    "training/parallel",
    "training/callbacks",
    "training/evaluation",
    "training/data_pipeline",
    "training/configs",
    "training/checkpoints/phase1/best_model",
    "training/checkpoints/phase2",
    "training/checkpoints/phase3",
    "training/checkpoints/final",
    "training/logs",
    "training/experiments/exp_001_baseline/logs",
    "training/experiments/exp_002_augmentation",
    "training/experiments/exp_003_security_weight",
    "training/launch",
    # inference
    "inference/core",
    "inference/optimization",
    "inference/hardware",
    "inference/servers",
    "inference/batch",
    "inference/caching",
    "inference/monitoring",
    "inference/configs",
    "inference/examples",
    "inference/benchmarks",
    # evaluation
    "evaluation/metrics",
    "evaluation/benchmarks/code_benchmarks",
    "evaluation/benchmarks/security_benchmarks",
    "evaluation/benchmarks/language_benchmarks",
    "evaluation/security_tests/adversarial",
    "evaluation/security_tests/robustness",
    "evaluation/security_tests/safety",
    "evaluation/security_tests/compliance",
    "evaluation/datasets/humaneval",
    "evaluation/datasets/custom_benchmarks",
    "evaluation/datasets/ground_truth",
    "evaluation/analysis",
    "evaluation/reports",
    "evaluation/visualization",
    "evaluation/logs",
    # api
    "api/rest/routes",
    "api/rest/middleware",
    "api/rest/models",
    "api/websocket",
    "api/graphql",
    "api/grpc/protos",
    "api/openapi/docs",
    "api/auth",
    "api/configs",
    "api/tests",
    # security
    "security/input_validation",
    "security/output_filtering",
    "security/access_control",
    "security/encryption",
    "security/threat_detection",
    "security/compliance",
    "security/vulnerability_scanning",
    "security/incident_response",
    "security/policy",
    "security/configs",
    # config
    "config/environments",
    "config/model_configs",
    "config/training_configs",
    "config/inference_configs",
    "config/data_configs",
    "config/logging",
    "config/monitoring",
    "config/distributed",
    "config/secrets",
    # utils - flat
    # tests
    "tests/unit",
    "tests/integration",
    "tests/performance",
    "tests/security",
    "tests/fixtures",
    "tests/benchmark",
    # docs
    "docs/examples",
    "docs/guides",
    "docs/api_reference",
    "docs/models",
    "docs/troubleshooting",
    "docs/images",
    # scripts
    "scripts/setup",
    "scripts/training",
    "scripts/inference",
    "scripts/deployment",
    "scripts/data",
    "scripts/maintenance",
    "scripts/monitoring",
    "scripts/development",
    # docker
    # kubernetes
    "kubernetes/api",
    "kubernetes/inference",
    "kubernetes/training",
    "kubernetes/monitoring",
    "kubernetes/logging",
    "kubernetes/networking",
    # notebooks
    "notebooks/data",
    # experiments
    "experiments/exp_001_baseline/logs",
    "experiments/exp_002_with_augmentation",
    "experiments/exp_003_security_weights",
    "experiments/exp_004_different_lr",
]

for rel in DIRS:
    path = ROOT / rel
    path.mkdir(parents=True, exist_ok=True)

print(f"Scaffold criado: {len(DIRS)} diretórios em {ROOT}")