FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
WORKDIR /app
COPY requirements.txt pyproject.toml ./
COPY training/ ./training/
COPY config/ ./config/
COPY utils/ ./utils/
COPY data/ ./data/
RUN pip install --no-cache-dir -e ".[training]"
CMD ["python", "-m", "training.core.trainer"]