apiVersion: v1
kind: ConfigMap
metadata:
  name: syon-config
  namespace: syon
data:
  SYON_API_HOST: "0.0.0.0"
  SYON_API_PORT: "8000"
  SYON_MODELS_DIR: "/models/pretrained"
  SYON_CORS_ORIGINS: "*"
  LOG_LEVEL: "INFO"